# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 18:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_auto_20160913_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('timeOf', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=11)),
                ('description', models.CharField(max_length=255)),
                ('timeOf', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('timeOf', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
        ),
    ]
