# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20161003_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Forum'),
        ),
    ]
