# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
    ]
